universe                = docker
docker_image            = ghcr.io/lkirk/tskit-ld/validation
docker_pull_policy      = always  # this means we always pull from the docker repo (see warnings in docs)

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = output.txt
arguments               = $(rep) $(seeds)

output			= outs/sim_$(Cluster)_$(Process).out
error                   = errs/sim_$(Cluster)_$(Process).err
log                     = log.$(Process)
request_memory          = 900M
request_disk            = 100M
queue rep,seeds

request_cpus = 1
request_memory = 1GB
request_disk = 1GB