universe                = docker
docker_image            = ghcr.io/lkirk/tskit-ld/spatial-ld-slim
docker_pull_policy      = always  # this means we always pull from the docker repo (see warnings in docs)

arguments               = -s $(seed) -d G=$(genome_len) -d sigma=$(sigma) -d outpath="'out'"

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = $(seed).tar.gz
transfer_output_remaps  = "$(seed).tar.gz = output-$(Cluster)/result/$(seed).tar.gz"

request_cpus            = 1
request_memory          = 4GB
request_disk            = 1GB
output                  = output-$(Cluster)/logs/out/$(Cluster)_$(Process).out
error                   = output-$(Cluster)/logs/err/$(Cluster)_$(Process).err
log                     = output-$(Cluster)/cluster.log

queue sigma,genome_len,seed from params.csv
