#!/bin/bash

set -euo pipefail

REPO_DIR="$(realpath "$(dirname "$(readlink -f "$0")")/..")"

[[ -e "$REPO_DIR/ve" ]] && (echo "$REPO_DIR/ve" exists, delete or move first; exit 1)
cd "$REPO_DIR"
python -m venv ve
source ve/bin/activate
pip install -e .
