#!/bin/bash

if [[ -z "$1" ]]; then
    echo "ERROR: missing input params csv"
    echo
    echo "usage: extract-logs-from-running-jobs <params_csv> <job_number>"
    exit 1
fi
if [[ -z "$2" ]]; then
    echo "ERROR: missing job number"
    echo
    echo "usage: extract-logs-from-running-jobs <params_csv> <job_number>"
    exit 1
fi
PARAMS_CSV="$1"
JOB_NUMBER="$2"

i=0
while read l; do
    d=logs/out/$(cut -f1,2 -d, <<<"$l"| sed -e's/,/_/g')
    mkdir -p "$d"
    condor_tail -maxbytes 100000 "${JOB_NUMBER}.$i" > "$d/outerr.log"
    ((i++))
done < "$PARAMS_CSV"
