#!/bin/bash

set -euo pipefail

OUTPATH="out"
SEED=""
for arg in $(seq 1 $#); do
    # if [[ "${!arg}" == outpath=* ]]; then
    # 	OUTPATH=$(tr -d "'" <<<"${!arg/outpath=/}")
    # fi
    if [[ "${!arg}" == "-s" ]]; then
	next_arg=$((arg + 1))
	SEED="${!next_arg}"
    fi
done

# if [[ -z "$OUTPATH" ]]; then
#     echo "No output path specified, use -d outpath=\"'/path/to/output'\"" >&2
#     exit 1
# fi
if [[ -z "$SEED" ]]; then
    echo "No seed specified, use -s <some integer>" >&2
    exit 1
fi

echo "Running slim with the following parameters:" "$@" -d "outpath="'"'"$OUTPATH"'"'"" /opt/main.slim
set -x
mkdir -p "$OUTPATH"
slim "$@" -d "outpath="'"'"$OUTPATH"'"'"" /opt/main.slim
tar -czvf "${SEED}.tar.gz" "${OUTPATH}"
rm -r "${OUTPATH}"
