#!/bin/bash

set -eo pipefail

# TODO: pass through args to SLiM??

ARGS=$(getopt -o h,s,p: --longoptions help,strip-prefix,param: -n entrypoint -- "$@")

usage () {
    echo "usage: entrypoint --param <param_path> [--strip-prefix]"
    exit 1
}

eval set -- "$ARGS"

STRIP_PREFIX=false
PARAM_FILE=''
while true; do
    case "$1" in
	-s | --strip-prefix) STRIP_PREFIX=true; shift ;;
	-p | --param) PARAM_FILE="$2"; shift 2;;
	-h | --help) usage;;
	-- ) shift; break;;
	* ) break;;
    esac
done

if [[ -z "$PARAM_FILE" ]]; then
    echo "ERROR: param file is a required argument"
    usage
fi

if [[ "$STRIP_PREFIX" = true ]]; then
    echo "Stripping params file prefix"
    PARAM_FILE="$(basename "$PARAM_FILE")"
fi

echo 'Running:' slim -d "PARAM_FILE="'"'"$PARAM_FILE"'"'"" /opt/main.slim
slim -d "PARAM_FILE="'"'"$PARAM_FILE"'"'"" /opt/main.slim
