name: Build and Publish Docker Image

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - name: validation
            context: validation/sim/docker
          - name: spatial-ld-slim
            context: spatial-ld/sim/docker
          - name: benchmarks
            context: benchmarks/sim/docker

    permissions:  # Sets the permissions granted to the `GITHUB_TOKEN`
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: metadata  # store tags/labels in this workflow id
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.container.name }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.container.context }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
